echo "compile_and_run j_script.j"
echo "line 1"
echo "line 2"
echo "1"
echo "2"
echo "done compiling script..."
echo "run j_script.j"
echo "1"
echo "2"
echo "print 1"
echo "print 2"
echo "done running script..."
