echo "var"
echo "cur_line"
echo "cur_line=0"
echo "cur_line=1"
echo "cur_line=2"
echo "cur_line=3"
echo "cur_line=4"
echo "cur_line=5"
echo "var"
echo "cur_letter"
echo "cur_letter=0"
echo "cur_letter=1"
echo "cur_letter=2"
echo "cur_letter=3"
echo "cur_letter=4"
echo "cur_letter=5"
echo ...
echo "store var"
echo "cur_line"
echo "set cur_line to 0"
echo "set cur_line to 1"
echo "set cur_line to 2"
echo "set cur_line to 3"
echo "set cur_line to 4"
echo "set cur_line to 5"
echo "store var"
echo "cur_letter"
echo "set cur_letter to 0"
echo "set cur_letter to 1"
echo "set cur_letter to 2"
echo "set cur_letter to 3"
echo "set cur_letter to 4"
echo "set cur_letter to 5"
echo "done interpreting lines."
echo ...
echo "CMD store var soon"
echo "CMD var name is cur_line"
echo "CMD set var soon"
echo "CMD var name is cur_line"
echo "CMD dest value is 0"
echo "CMD set var soon"
echo "CMD var name is cur_line"
echo "CMD dest value is 1"
echo "CMD set var soon"
echo "CMD var name is cur_line"
echo "CMD dest value is 2"
echo "CMD set var soon"
echo "CMD var name is cur_line"
echo "CMD dest value is 3"
echo "CMD set var soon"
echo "CMD var name is cur_line"
echo "CMD dest value is 4"
echo "CMD set var soon"
echo "CMD var name is cur_line"
echo "CMD dest value is 5"
echo "CMD store var soon"
echo "CMD var name is cur_letter"
echo "CMD set var soon"
echo "CMD var name is cur_letter"
echo "CMD dest value is 0"
echo "CMD var name is cur_letter"
echo "CMD dest value is 1"
echo "CMD set var soon"
echo "CMD var name is cur_letter"
echo "CMD dest value is 2"
echo "CMD set var soon"
echo "CMD var name is cur_letter"
echo "CMD dest value is 3"
echo "CMD set var soon"
echo "CMD var name is cur_letter"
echo "CMD dest value is 4"
echo "CMD set var soon"
echo "CMD var name is cur_letter"
echo "CMD dest value is 5"
echo "done making the CMD tokens list"
echo ...
echo "31"
echo "32"
echo "33"
echo "34"
echo "35"
echo "36"
echo "37"
echo "38"
echo "39"
echo "40"
echo "41"
echo "42"
echo "43"
echo "44"
echo "45"
echo "46"
echo "47"
echo "48"
echo "49"
echo "50"
echo "51"
echo "52"
echo "53"
echo "54"
echo "55"
echo "56"
echo "57"
echo "58"
echo "59"
echo "60"
echo "61"
echo "62"
echo "63"
echo "64"
echo "65"
echo "66"
echo "67"
echo "68"
echo "69"
echo "done."
echo "..."
echo "main.bat"
echo "main.j"
echo "aux_j_script_1.j"
echo "aux_j_script_2.j"
echo "aux_j_script_3.j"
echo "linereader.jd"
echo "compile_and_run_linereader_jd_script_fully.bat"
echo "main_BatchImplemEntryPointScript1_cycleloop.bat"
echo "linereader_jd_bytecode.txt"
echo "main_BatchImplemEntryPointScript1_cycleloop.bat"
echo "callback every so many frames"
echo "linereader_jd_bytecode.txt, callback update loop would be here"
echo "..."
