echo "var"
echo "cur_line"
echo "cur_line = 0"
echo "1"
echo "2"
echo "3"
echo "linereader.jd"
echo "linereader_jd_script_bytecode.txt"
echo "bytecode"
echo "1"
echo "2"
echo "3"
echo "var"
echo "cur_line"
echo "cur_line = 0"
echo "made variable"
echo "called the variable cur_line"
echo "set the variable called cur_line to value of 0"
echo "make var"
echo "call_var cur_line"
echo "set_var cur_line value_of 0"
echo "store_var"
echo "cur_line"
echo "set_var"
echo "0"
