echo "var player;"
echo "var level;"
echo "var menu;"
echo "var enemy;"
echo "player = 41;"
echo "level = 42;"
echo "menu = 43;"
echo "enemy = 44;"
echo "var player_move_right_counter;"
echo "player_move_right_counter = 0;"
echo "player_move_right_counter = 1;"
echo "player_move_right_counter = 2;"
echo "player_move_right_counter = 3;"
echo "var printedValue;"
echo "printedValue = player_move_right_counter;"
echo "151"
echo "152"
echo "153"
echo "154"
echo "155"
echo "156"
echo "157"
echo "158"
echo "159"
echo "160"
echo "170"
echo "171"
echo "172"
echo "173"
