echo "J PROGRAM COMPILER"
echo "J PROGRAM COMPILER: compile and run tinyxml_code_project_run_function.j"
echo "J PROGRAM COMPILER: script line strings..."
echo "var tinyxml_code_file_1;"
echo "var tinyxml_code_file_2;"
echo "var tinyxml_code_file_3;"
echo " "
echo "tinyxml_code_file_1 = 0;"
echo "tinyxml_code_file_2 = 0;"
echo "tinyxml_code_file_3 = 0;"
echo " "
echo "var file_1_label_1_number;"
echo "var file_1_label_2_number;"
echo "var file_1_label_3_number;"
echo "var file_1_label_4_number;"
echo " "
echo "file_1_label_1_number = 0;"
echo "file_1_label_2_number = 0;"
echo "file_1_label_3_number = 0;"
echo "file_1_label_4_number = 0;"
echo " "
echo "var file_1_label_1_string;"
echo "var file_1_label_2_string;"
echo "var file_1_label_3_string;"
echo "var file_1_label_4_string;"
echo " "
echo "var temp_string;"
echo " "
echo "file_1_label_1_string = 0;"
echo "file_1_label_2_string = 0;"
echo "file_1_label_3_string = 0;"
echo "file_1_label_4_string = 0;"
echo " "
echo "temp_string = 0;"
echo " "
echo "var myString1;"
echo "var myString2;"
echo "var myBoolean1;"
echo " "
echo "myString1 = 0;"
echo "myString2 = 0;"
echo "myBoolean1 = 0;"
echo " "
echo "var myPrintConsoleLine1String;"
echo "var myPrintConsoleLine2String;"
echo "var myPrintConsoleLine3String;"
echo " "
echo "var myPrintConsoleLine4String;"
echo "var myPrintConsoleLine5String;"
echo "var myPrintConsoleLine6String;"
echo " "
echo "var myPrintConsoleLine7String;"
echo "var myPrintConsoleLine8String;"
echo "var myPrintConsoleLine9String;"
echo " "
echo "var myPrintConsoleLine10String;"
echo "var myPrintConsoleLine11String;"
echo "var myPrintConsoleLine12String;"
echo " "
echo "var myPrintConsoleLine13String;"
echo "var myPrintConsoleLine14String;"
echo "var myPrintConsoleLine15String;"
echo " "
echo "var myPrintValue;"
echo " "
echo "myPrintConsoleLine1String = 0;"
echo "myPrintConsoleLine2String = 0;"
echo "myPrintConsoleLine3String = 0;"
echo " "
echo "myPrintConsoleLine4String = 0;"
echo "myPrintConsoleLine5String = 0;"
echo "myPrintConsoleLine6String = 0;"
echo " "
echo "myPrintConsoleLine7String = 0;"
echo "myPrintConsoleLine8String = 0;"
echo "myPrintConsoleLine9String = 0;"
echo " "
echo "myPrintConsoleLine10String = 0;"
echo "myPrintConsoleLine11String = 0;"
echo "myPrintConsoleLine12String = 0;"
echo " "
echo "myPrintConsoleLine13String = 0;"
echo "myPrintConsoleLine14String = 0;"
echo "myPrintConsoleLine15String = 0;"
echo " "
echo "myPrintValue = 0;"
echo " "
echo "func MyScriptPrintFunction() {"
echo "  myPrintValue = file_1_label_1_string;"
echo "  myPrintConsoleLine1String = myPrintValue;"
echo "  "
echo "  myPrintValue = file_1_label_2_string;"
echo "  myPrintConsoleLine2String = myPrintValue;"
echo "  "
echo "  myPrintValue = file_1_label_3_string;"
echo "  myPrintConsoleLine3String = myPrintValue;"
echo "  "
echo "  myPrintValue = file_1_label_4_string;"
echo "  myPrintConsoleLine4String = myPrintValue;"
echo " "
echo " "
echo "func MyScriptRunFunction() {"
echo "  tinyxml_code_file_1 = 1;"
echo "  tinyxml_code_file_2 = 2;"
echo "  tinyxml_code_file_3 = 3;"
echo "  "
echo "  file_1_label_1_number = 101;"
echo "  file_1_label_2_number = 102;"
echo "  file_1_label_3_number = 103;"
echo "  file_1_label_4_number = 104;"
echo "  "
echo "  var temp_string_value_This_is_a_paragraph_for_label_1_;"  
echo "  temp_string_value_This_is_a_paragraph_for_label_1_ = 6001;"
echo "  "
echo "  temp_string = temp_string_value_This_is_a_paragraph_for_label_1_;"
echo "  "
echo "  file_1_label_1_string = temp_string;"
echo "  "
echo "  var temp_string_value_This_is_a_paragraph_for_label_2_;"  
echo "  temp_string_value_This_is_a_paragraph_for_label_2_ = 6002;"
echo "  "
echo "  temp_string = temp_string_value_This_is_a_paragraph_for_label_2_;"
echo "  "
echo "  file_1_label_2_string = temp_string;"
echo "  "
echo "  var temp_string_value_This_is_a_paragraph_for_label_3_;"  
echo "  temp_string_value_This_is_a_paragraph_for_label_3_ = 6003;"
echo "  "
echo "  temp_string = temp_string_value_This_is_a_paragraph_for_label_3_;"
echo "  "
echo "  file_1_label_3_string = temp_string;"
echo "  "
echo "  var temp_string_value_This_is_a_paragraph_for_label_4_;"  
echo "  temp_string_value_This_is_a_paragraph_for_label_4_ = 6004;"
echo "  "
echo "  file_1_label_4_string = temp_string;"
echo "  "
echo "  MyScriptPrintFunction();"
echo "}"
echo " "
echo "MyScriptRunFunction();"
echo "J PROGRAM COMPILER: end of script line strings..."
echo "J PROGRAM COMPILER: script line command numbers..."
echo "185"
echo "186"
echo "187"
echo "188"
echo "189"
echo "tinyxml_code_file_1 = 0;"
echo "tinyxml_code_file_2 = 0;"
echo "tinyxml_code_file_3 = 0;"
echo " "
echo "var file_1_label_1_number;"
echo "var file_1_label_2_number;"
echo "var file_1_label_3_number;"
echo "var file_1_label_4_number;"
echo " "
echo "file_1_label_1_number = 0;"
echo "file_1_label_2_number = 0;"
echo "file_1_label_3_number = 0;"
echo "file_1_label_4_number = 0;"
echo " "
echo "var file_1_label_1_string;"
echo "var file_1_label_2_string;"
echo "var file_1_label_3_string;"
echo "var file_1_label_4_string;"
echo " "
echo "var temp_string;"
echo " "
echo "file_1_label_1_string = 0;"
echo "file_1_label_2_string = 0;"
echo "file_1_label_3_string = 0;"
echo "file_1_label_4_string = 0;"
echo " "
echo "temp_string = 0;"
echo " "
echo "var myString1;"
echo "var myString2;"
echo "var myBoolean1;"
echo " "
echo "myString1 = 0;"
echo "myString2 = 0;"
echo "myBoolean1 = 0;"
echo " "
echo "var myPrintConsoleLine1String;"
echo "var myPrintConsoleLine2String;"
echo "var myPrintConsoleLine3String;"
echo " "
echo "var myPrintConsoleLine4String;"
echo "var myPrintConsoleLine5String;"
echo "var myPrintConsoleLine6String;"
echo " "
echo "var myPrintConsoleLine7String;"
echo "var myPrintConsoleLine8String;"
echo "var myPrintConsoleLine9String;"
echo " "
echo "var myPrintConsoleLine10String;"
echo "var myPrintConsoleLine11String;"
echo "var myPrintConsoleLine12String;"
echo " "
echo "var myPrintConsoleLine13String;"
echo "var myPrintConsoleLine14String;"
echo "var myPrintConsoleLine15String;"
echo " "
echo "var myPrintValue;"
echo " "
echo "myPrintConsoleLine1String = 0;"
echo "myPrintConsoleLine2String = 0;"
echo "myPrintConsoleLine3String = 0;"
echo " "
echo "myPrintConsoleLine4String = 0;"
echo "myPrintConsoleLine5String = 0;"
echo "myPrintConsoleLine6String = 0;"
echo " "
echo "myPrintConsoleLine7String = 0;"
echo "myPrintConsoleLine8String = 0;"
echo "myPrintConsoleLine9String = 0;"
echo " "
echo "myPrintConsoleLine10String = 0;"
echo "myPrintConsoleLine11String = 0;"
echo "myPrintConsoleLine12String = 0;"
echo " "
echo "myPrintConsoleLine13String = 0;"
echo "myPrintConsoleLine14String = 0;"
echo "myPrintConsoleLine15String = 0;"
echo " "
echo "myPrintValue = 0;"
echo " "
echo "func MyScriptPrintFunction() {"
echo "  myPrintValue = file_1_label_1_string;"
echo "  myPrintConsoleLine1String = myPrintValue;"
echo "  "
echo "  myPrintValue = file_1_label_2_string;"
echo "  myPrintConsoleLine2String = myPrintValue;"
echo "  "
echo "  myPrintValue = file_1_label_3_string;"
echo "  myPrintConsoleLine3String = myPrintValue;"
echo "  "
echo "  myPrintValue = file_1_label_4_string;"
echo "  myPrintConsoleLine4String = myPrintValue;"
echo " "
echo " "
echo "func MyScriptRunFunction() {"
echo "  tinyxml_code_file_1 = 1;"
echo "  tinyxml_code_file_2 = 2;"
echo "  tinyxml_code_file_3 = 3;"
echo "  "
echo "  file_1_label_1_number = 101;"
echo "  file_1_label_2_number = 102;"
echo "  file_1_label_3_number = 103;"
echo "  file_1_label_4_number = 104;"
echo "  "
echo "  var temp_string_value_This_is_a_paragraph_for_label_1_;"  
echo "  temp_string_value_This_is_a_paragraph_for_label_1_ = 6001;"
echo "  "
echo "  temp_string = temp_string_value_This_is_a_paragraph_for_label_1_;"
echo "  "
echo "  file_1_label_1_string = temp_string;"
echo "  "
echo "  var temp_string_value_This_is_a_paragraph_for_label_2_;"  
echo "  temp_string_value_This_is_a_paragraph_for_label_2_ = 6002;"
echo "  "
echo "  temp_string = temp_string_value_This_is_a_paragraph_for_label_2_;"
echo "  "
echo "  file_1_label_2_string = temp_string;"
echo "  "
echo "  var temp_string_value_This_is_a_paragraph_for_label_3_;"  
echo "  temp_string_value_This_is_a_paragraph_for_label_3_ = 6003;"
echo "  "
echo "  temp_string = temp_string_value_This_is_a_paragraph_for_label_3_;"
echo "  "
echo "  file_1_label_3_string = temp_string;"
echo "  "
echo "  var temp_string_value_This_is_a_paragraph_for_label_4_;"  
echo "  temp_string_value_This_is_a_paragraph_for_label_4_ = 6004;"
echo "  "
echo "  file_1_label_4_string = temp_string;"
echo "  "
echo "  MyScriptPrintFunction();"
echo "}"
echo " "
echo "MyScriptRunFunction();"
echo "J PROGRAM COMPILER: end of script line command numbers..."