CALL script_1.bat
CALL script_2.bat
CALL script_3.bat
CALL script_4.bat
CALL script_5.bat
ECHO #####
ECHO #####
ECHO #####
ECHO #####
CALL script_19.bat
CALL script_19.bat
ECHO #####
ECHO #####
ECHO #####
ECHO #####
ECHO #####
