echo "linereader.jd"
echo "var"
echo "cur_line"
echo "cur_line=0"
echo "cur_line=1"
echo "cur_line=2"
echo "cur_line=3"
echo "cur_line=4"
echo "cur_line=5"
echo "var"
echo "cur_letter"
echo "cur_letter=0"
echo "cur_letter=1"
echo "cur_letter=2"
echo "cur_letter=3"
echo "cur_letter=4"
echo "cur_letter=5"
echo "done printing lines."
echo ...
echo "store var"
echo "cur_line"
echo "set cur_line to 0"
echo "set cur_line to 1"
echo "set cur_line to 2"
echo "set cur_line to 3"
echo "set cur_line to 4"
echo "set cur_line to 5"
echo "store var"
echo "cur_letter"
echo "set cur_letter to 0"
echo "set cur_letter to 1"
echo "set cur_letter to 2"
echo "set cur_letter to 3"
echo "set cur_letter to 4"
echo "set cur_letter to 5"
echo "done interpreting lines."
echo ...
echo "CMD store var soon"
echo "CMD var name is cur_line"
echo "CMD set var soon"
echo "CMD var name is cur_line"
echo "CMD dest value is 0"
echo "CMD set var soon"
echo "CMD var name is cur_line"
echo "CMD dest value is 1"
echo "CMD set var soon"
echo "CMD var name is cur_line"
echo "CMD dest value is 2"
echo "CMD set var soon"
echo "CMD var name is cur_line"
echo "CMD dest value is 3"
echo "CMD set var soon"
echo "CMD var name is cur_line"
echo "CMD dest value is 4"
echo "CMD set var soon"
echo "CMD var name is cur_line"
echo "CMD dest value is 5"
echo "CMD store var soon"
echo "CMD var name is cur_letter"
echo "CMD set var soon"
echo "CMD var name is cur_letter"
echo "CMD dest value is 0"
echo "CMD var name is cur_letter"
echo "CMD dest value is 1"
echo "CMD set var soon"
echo "CMD var name is cur_letter"
echo "CMD dest value is 2"
echo "CMD set var soon"
echo "CMD var name is cur_letter"
echo "CMD dest value is 3"
echo "CMD set var soon"
echo "CMD var name is cur_letter"
echo "CMD dest value is 4"
echo "CMD set var soon"
echo "CMD var name is cur_letter"
echo "CMD dest value is 5"
echo "done making the CMD tokens list"
echo ...
echo "done running this script called linereader.jd"
echo "done."
echo "..."
