echo "var a;"
echo "var b;"
echo "var c;"
echo "\n"
echo "func Iterate() {"
echo "  var i;"
echo "  i = 0;"
echo "  i = 1;"
echo "  i = 2;"
echo "  i = 3;"
echo "  i = 4;"
echo "  i = 5;"
echo "  i = 6;"
echo "  i = 7;"
echo "  i = 8;"
echo "  i = 9;"
echo "  i = 10;"
echo "  i = 11;"
echo "  i = 12;"
echo "  i = 13;"
echo "  i = 14;"
echo "  i = 15;"
echo "  i = 16;"
echo "  i = 17;"
echo "  i = 18;"
echo "  i = 19;"
echo "  i = 20;"
echo "  i = 21;"
echo "  i = 22;"
echo "  i = 23;"
echo "  i = 24;"
echo "  i = 25;"
echo "}"
echo "\n"
echo "func Loop() {"
echo "  var iterations;"
echo "  iterations = 3;"
echo "\n"
echo "  var max_iterations;"
echo "  max_iterations = 1000;"
echo "  ";
echo "  var max_iterations_2;"
echo "  max_iterations_2 = 1000000;"
echo "  "
echo "  var iteration_counter;"
echo "  iteration_counter = 0;"
echo "  "
echo "  Iterate();"
echo "  Iterate();"
echo "  Iterate();"
echo "  "
echo "  iteration_counter = 3;"
echo "  "
echo "  var temp_iteration_counter;"
echo "  temp_iteration_counter = 0;"
echo ""
echo "done printing lines."