echo "var a;"
echo "var b;"
echo "var c;"
echo "\n"
echo "func Iterate() {"
echo "  var i;"
echo "  i = 0;"
echo "  i = 1;"
echo "  i = 2;"
echo "  i = 3;"
echo "  i = 4;"
echo "  i = 5;"
echo "  i = 6;"
echo "  i = 7;"
echo "  i = 8;"
echo "  i = 9;"
echo "  i = 10;"
echo "  i = 11;"
echo "  i = 12;"
echo "  i = 13;"
echo "  i = 14;"
echo "  i = 15;"
echo "  i = 16;"
echo "  i = 17;"
echo "  i = 18;"
echo "  i = 19;"
echo "  i = 20;"
echo "  i = 21;"
echo "  i = 22;"
echo "  i = 23;"
echo "  i = 24;"
echo "  i = 25;"
echo "}"
echo "\n"
echo "func Loop() {"
echo "  var iterations;"
echo "  iterations = 3;"
echo "\n"
echo "  var max_iterations;"
echo "  max_iterations = 1000;"
echo "  ";
echo "  var max_iterations_2;"
echo "  max_iterations_2 = 1000000;"
echo "  "
echo "  var iteration_counter;"
echo "  iteration_counter = 0;"
echo "  "
echo "  Iterate();"
echo "  Iterate();"
echo "  Iterate();"
echo "  "
echo "  iteration_counter = 3;"
echo "  "
echo "  var temp_iteration_counter;"
echo "  temp_iteration_counter = 0;"
echo "  temp_iteration_counter = max_iterations;"
echo "  "
echo "  temp_iteration_counter = max_iterations_2;"
echo "}"
echo "\n"
echo "func LightScript() {"
echo ""
echo "  a = 1;"
echo "  b = 2;"
echo "  c = 3;"
echo "  "
echo "  Iterate();"
echo "  Loop();"
echo "}"
echo "done printing lines."
echo "var a;, store var, called a"
echo "var b;, store var, called b"
echo "var c;, store var, called c"
echo "\n, newline"
echo "func Iterate() {, store func, called Iterate"
echo "  var i;, store var, called i"
echo "  i = 0;, set var, called i, to value of 0"
echo "  i = 1;, set var, called i, to value of 1"
echo "  i = 2;, set var, called i, to value of 2"
echo "  i = 3;, set var, called i, to value of 3"
echo "  i = 4;, set var, called i, to value of 4"
echo "  i = 5;, set var, called i, to value of 5"
echo "  i = 6;, set var, called i, to value of 6"
echo "  i = 7;, set var, called i, to value of 7"
echo "  i = 8;, set var, called i, to value of 8"
echo "  i = 9;, set var, called i, to value of 9"
echo "  i = 10;, set var, called i, to value of 10"
echo "  i = 11;, set var, called i, to value of 11"
echo "  i = 12;, set var, called i, to value of 12"
echo "  i = 13;, set var, called i, to value of 13"
echo "  i = 14;, set var, called i, to value of 14"
echo "  i = 15;, set var, called i, to value of 15"
echo "  i = 16;, set var, called i, to value of 16"
echo "  i = 17;, set var, called i, to value of 17"
echo "  i = 18;, set var, called i, to value of 18"
echo "  i = 19;, set var, called i, to value of 19"
echo "  i = 20;, set var, called i, to value of 20"
echo "  i = 21;, set var, called i, to value of 21"
echo "  i = 22;, set var, called i, to value of 22"
echo "  i = 23;, set var, called i, to value of 23"
echo "  i = 24;, set var, called i, to value of 24"
echo "  i = 25;, set var, called i, to value of 25"
echo "}, end store func"
echo "\n, newline"
echo "func Loop() {, store func, called Loop"
echo "  var iterations;, store var, called iterations"
echo "  iterations = 3;, set var, called iterations, to value of 3"
echo "\n, newline"
echo "  var max_iterations;, store var, called max_iterations"
echo "  max_iterations = 1000;, set var, called max_iterations to value of 1000"
echo "  , newline"
echo "  var max_iterations_2;, store var, called max_iterations_2"
echo "  max_iterations_2 = 1000000;, set var, called max_iterations_2, to value of 1000000"
echo "  , newline"
echo "  var iteration_counter;, store var, called iteration_counter"
echo "  iteration_counter = 0;, set var, called iteration_counter"
echo "  , newline"
echo "  Iterate();, call func, called Iterate"
echo "  Iterate();, call func, called Iterate"
echo "  Iterate();, call func, called Iterate"
echo "  , newline"
echo "  iteration_counter = 3;, set var, called iteration_counter, to value of 3"
echo "  , newline"
echo "  var temp_iteration_counter;, store var, called temp_iteration_counter"
echo "  temp_iteration_counter = 0;, set var, called temp_iteration_counter, to value of 0"
echo "  temp_iteration_counter = max_iterations;, set var, called temp_iteration_counter, to value of max_iterations"
echo "  , newline"
echo "  temp_iteration_counter = max_iterations_2;, set var, called temp_iteration_counter, to value of max_iterations_2"
echo "}, end store func"
echo "\n, newline"
echo "func LightScript() {, store func, called LightScript"
echo "newline"
echo "  a = 1;, set var, called a, to value of 1"
echo "  b = 2;, set var, called b, to value of 2"
echo "  c = 3;, set var, called c, to value of 3"
echo "  , newline"
echo "  Iterate();, call func, called Iterate"
echo "  Loop();, call func, called Loop"
echo "}, newline"
echo "done interpreting lines, as console command lines."
echo "var a;, store var, called a, 71"
echo "var b;, store var, called b, 72"
echo "var c;, store var, called c, 73"
echo "\n, newline, 74"
echo "func Iterate() {, store func, called Iterate, 75"
echo "  var i;, store var, called i, 76"
echo "  i = 0;, set var, called i, to value of 0, 77"
echo "  i = 1;, set var, called i, to value of 1, 78"
echo "  i = 2;, set var, called i, to value of 2, 79"
echo "  i = 3;, set var, called i, to value of 3, 80"
echo "  i = 4;, set var, called i, to value of 4, 81"
echo "  i = 5;, set var, called i, to value of 5, 82"
echo "  i = 6;, set var, called i, to value of 6, 83"
echo "  i = 7;, set var, called i, to value of 7, 84"
echo "  i = 8;, set var, called i, to value of 8, 85"
echo "  i = 9;, set var, called i, to value of 9, 86"
echo "  i = 10;, set var, called i, to value of 10, 87"
echo "  i = 11;, set var, called i, to value of 11, 88"
echo "  i = 12;, set var, called i, to value of 12, 89"
echo "  i = 13;, set var, called i, to value of 13, 90"
echo "  i = 14;, set var, called i, to value of 14, 91"
echo "  i = 15;, set var, called i, to value of 15, 92"
echo "  i = 16;, set var, called i, to value of 16, 93"
echo "  i = 17;, set var, called i, to value of 17, 94"
echo "  i = 18;, set var, called i, to value of 18, 95"
echo "  i = 19;, set var, called i, to value of 19, 96"
echo "  i = 20;, set var, called i, to value of 20, 97"
echo "  i = 21;, set var, called i, to value of 21, 98"
echo "  i = 22;, set var, called i, to value of 22, 99"
echo "  i = 23;, set var, called i, to value of 23, 100"
echo "  i = 24;, set var, called i, to value of 24, 101"
echo "  i = 25;, set var, called i, to value of 25, 102"
echo "}, end store func, 103"
echo "\n, newline, 104"
echo "func Loop() {, store func, called Loop, 105"
echo "  var iterations;, store var, called iterations, 106"
echo "  iterations = 3;, set var, called iterations, to value of 3, 107"
echo "\n, newline, 108"
echo "  var max_iterations;, store var, called max_iterations, 109"
echo "  max_iterations = 1000;, set var, called max_iterations to value of 1000, 110"
echo "  , newline, 111"
echo "  var max_iterations_2;, store var, called max_iterations_2, 112"
echo "  max_iterations_2 = 1000000;, set var, called max_iterations_2, to value of 1000000, 113"
echo "  , newline, 114"
echo "  var iteration_counter;, store var, called iteration_counter, 115"
echo "  iteration_counter = 0;, set var, called iteration_counter, 116"
echo "  , newline, 117"
echo "  Iterate();, call func, called Iterate, 118"
echo "  Iterate();, call func, called Iterate, 119"
echo "  Iterate();, call func, called Iterate, 120"
echo "  , newline, 121"
echo "  iteration_counter = 3;, set var, called iteration_counter, to value of 3, 122"
echo "  , newline, 123"
echo "  var temp_iteration_counter;, store var, called temp_iteration_counter, 124"
echo "  temp_iteration_counter = 0;, set var, called temp_iteration_counter, to value of 0, 125"
echo "  temp_iteration_counter = max_iterations;, set var, called temp_iteration_counter, to value of max_iterations, 126"
echo "  , newline, 128"
echo "  temp_iteration_counter = max_iterations_2;, set var, called temp_iteration_counter, to value of max_iterations_2, 129"
echo "}, end store func, 130"
echo "\n, newline, 132"
echo "func LightScript() {, store func, called LightScript, 133"
echo "newline, 134"
echo "  a = 1;, set var, called a, to value of 1, 135"
echo "  b = 2;, set var, called b, to value of 2, 136"
echo "  c = 3;, set var, called c, to value of 3, 137"
echo "  , newline, 139"
echo "  Iterate();, call func, called Iterate, 140"
echo "  Loop();, call func, called Loop, 141"
echo "}, newline, 142"
echo "done writing console command lines, as console command numbers."
echo "var a;, store var, called a, 71, use command 71"
echo "var b;, store var, called b, 72, use command 72"
echo "var c;, store var, called c, 73, use command 73"
echo "done using console command numbers (example snippet)"
echo "var a;, store var, called a, 71, from command 71"
echo "var b;, store var, called b, 72, from command 72"
echo "var c;, store var, called c, 73, from command 73"
echo "x, from command 31"
echo "picture_movie, from command 37"
echo "done returning where the command numbers were used from"
echo "done compiling and running LightScript.j"
echo "..."
