echo "c_bytecode"
echo "j_bytecode"
echo "1"
echo "1"
echo "2"
echo "2"
echo "3"
echo "3"
echo "c_interpret"
echo "j_interpret"
echo "command number 1"
echo "command number 1"
echo "command number 2"
echo "command number 2"
echo "command number 3"
echo "command number 3"
