echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "__#####______"
echo "_#   ##______"
echo "#######______"
echo "#   # #______"
echo "#   # #______"
echo "######_______"
echo "COMMENT FRAME 1 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_#   ##______"
echo "#######______"
echo "##   ##______"
echo "##   ##______"
echo "#######_______"
echo "COMMENT FRAME 2 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_##   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 3 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "######_______"
echo "###   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 4 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "#######______"
echo "# #    #______"
echo "########______"
echo "# #    #______"
echo "# #    #______"
echo "########______"
echo "COMMENT FRAME 5 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "__#####______"
echo "_#   ##______"
echo "#######______"
echo "#   # #______"
echo "#   # #______"
echo "######_______"
echo "COMMENT FRAME 1 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_#   ##______"
echo "#######______"
echo "##   ##______"
echo "##   ##______"
echo "#######_______"
echo "COMMENT FRAME 2 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_##   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 3 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "######_______"
echo "###   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 4 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "#######______"
echo "# #    #______"
echo "########______"
echo "# #    #______"
echo "# #    #______"
echo "########______"
echo "COMMENT FRAME 5 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "__#####______"
echo "_#   ##______"
echo "#######______"
echo "#   # #______"
echo "#   # #______"
echo "######_______"
echo "COMMENT FRAME 1 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_#   ##______"
echo "#######______"
echo "##   ##______"
echo "##   ##______"
echo "#######_______"
echo "COMMENT FRAME 2 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_##   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 3 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "######_______"
echo "###   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 4 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "#######______"
echo "# #    #______"
echo "########______"
echo "# #    #______"
echo "# #    #______"
echo "########______"
echo "COMMENT FRAME 5 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "__#####______"
echo "_#   ##______"
echo "#######______"
echo "#   # #______"
echo "#   # #______"
echo "######_______"
echo "COMMENT FRAME 1 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_#   ##______"
echo "#######______"
echo "##   ##______"
echo "##   ##______"
echo "#######_______"
echo "COMMENT FRAME 2 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_##   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 3 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "######_______"
echo "###   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 4 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "#######______"
echo "# #    #______"
echo "########______"
echo "# #    #______"
echo "# #    #______"
echo "########______"
echo "COMMENT FRAME 5 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "__#####______"
echo "_#   ##______"
echo "#######______"
echo "#   # #______"
echo "#   # #______"
echo "######_______"
echo "COMMENT FRAME 1 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_#   ##______"
echo "#######______"
echo "##   ##______"
echo "##   ##______"
echo "#######_______"
echo "COMMENT FRAME 2 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_##   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 3 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "######_______"
echo "###   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 4 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "#######______"
echo "# #    #______"
echo "########______"
echo "# #    #______"
echo "# #    #______"
echo "########______"
echo "COMMENT FRAME 5 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "__#####______"
echo "_#   ##______"
echo "#######______"
echo "#   # #______"
echo "#   # #______"
echo "######_______"
echo "COMMENT FRAME 1 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_#   ##______"
echo "#######______"
echo "##   ##______"
echo "##   ##______"
echo "#######_______"
echo "COMMENT FRAME 2 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_##   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 3 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "######_______"
echo "###   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 4 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "#######______"
echo "# #    #______"
echo "########______"
echo "# #    #______"
echo "# #    #______"
echo "########______"
echo "COMMENT FRAME 5 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "__#####______"
echo "_#   ##______"
echo "#######______"
echo "#   # #______"
echo "#   # #______"
echo "######_______"
echo "COMMENT FRAME 1 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_#   ##______"
echo "#######______"
echo "##   ##______"
echo "##   ##______"
echo "#######_______"
echo "COMMENT FRAME 2 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_##   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 3 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "######_______"
echo "###   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 4 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "#######______"
echo "# #    #______"
echo "########______"
echo "# #    #______"
echo "# #    #______"
echo "########______"
echo "COMMENT FRAME 5 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "__#####______"
echo "_#   ##______"
echo "#######______"
echo "#   # #______"
echo "#   # #______"
echo "######_______"
echo "COMMENT FRAME 1 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_#   ##______"
echo "#######______"
echo "##   ##______"
echo "##   ##______"
echo "#######_______"
echo "COMMENT FRAME 2 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_##   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 3 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "######_______"
echo "###   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 4 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "#######______"
echo "# #    #______"
echo "########______"
echo "# #    #______"
echo "# #    #______"
echo "########______"
echo "COMMENT FRAME 5 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "__#####______"
echo "_#   ##______"
echo "#######______"
echo "#   # #______"
echo "#   # #______"
echo "######_______"
echo "COMMENT FRAME 1 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_#   ##______"
echo "#######______"
echo "##   ##______"
echo "##   ##______"
echo "#######_______"
echo "COMMENT FRAME 2 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_##   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 3 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "######_______"
echo "###   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 4 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "#######______"
echo "# #    #______"
echo "########______"
echo "# #    #______"
echo "# #    #______"
echo "########______"
echo "COMMENT FRAME 5 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "__#####______"
echo "_#   ##______"
echo "#######______"
echo "#   # #______"
echo "#   # #______"
echo "######_______"
echo "COMMENT FRAME 1 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_#   ##______"
echo "#######______"
echo "##   ##______"
echo "##   ##______"
echo "#######_______"
echo "COMMENT FRAME 2 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_##   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 3 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "######_______"
echo "###   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 4 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "#######______"
echo "# #    #______"
echo "########______"
echo "# #    #______"
echo "# #    #______"
echo "########______"
echo "COMMENT FRAME 5 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "__#####______"
echo "_#   ##______"
echo "#######______"
echo "#   # #______"
echo "#   # #______"
echo "######_______"
echo "COMMENT FRAME 1 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_#   ##______"
echo "#######______"
echo "##   ##______"
echo "##   ##______"
echo "#######_______"
echo "COMMENT FRAME 2 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_##   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 3 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "######_______"
echo "###   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 4 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "#######______"
echo "# #    #______"
echo "########______"
echo "# #    #______"
echo "# #    #______"
echo "########______"
echo "COMMENT FRAME 5 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "__#####______"
echo "_#   ##______"
echo "#######______"
echo "#   # #______"
echo "#   # #______"
echo "######_______"
echo "COMMENT FRAME 1 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_#   ##______"
echo "#######______"
echo "##   ##______"
echo "##   ##______"
echo "#######_______"
echo "COMMENT FRAME 2 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_##   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 3 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "######_______"
echo "###   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 4 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "#######______"
echo "# #    #______"
echo "########______"
echo "# #    #______"
echo "# #    #______"
echo "########______"
echo "COMMENT FRAME 5 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "__#####______"
echo "_#   ##______"
echo "#######______"
echo "#   # #______"
echo "#   # #______"
echo "######_______"
echo "COMMENT FRAME 1 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_#   ##______"
echo "#######______"
echo "##   ##______"
echo "##   ##______"
echo "#######_______"
echo "COMMENT FRAME 2 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_##   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 3 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "######_______"
echo "###   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 4 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "#######______"
echo "# #    #______"
echo "########______"
echo "# #    #______"
echo "# #    #______"
echo "########______"
echo "COMMENT FRAME 5 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "__#####______"
echo "_#   ##______"
echo "#######______"
echo "#   # #______"
echo "#   # #______"
echo "######_______"
echo "COMMENT FRAME 1 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_#   ##______"
echo "#######______"
echo "##   ##______"
echo "##   ##______"
echo "#######_______"
echo "COMMENT FRAME 2 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_##   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 3 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "######_______"
echo "###   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 4 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "#######______"
echo "# #    #______"
echo "########______"
echo "# #    #______"
echo "# #    #______"
echo "########______"
echo "COMMENT FRAME 5 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "__#####______"
echo "_#   ##______"
echo "#######______"
echo "#   # #______"
echo "#   # #______"
echo "######_______"
echo "COMMENT FRAME 1 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_#   ##______"
echo "#######______"
echo "##   ##______"
echo "##   ##______"
echo "#######_______"
echo "COMMENT FRAME 2 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_##   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 3 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "######_______"
echo "###   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 4 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "#######______"
echo "# #    #______"
echo "########______"
echo "# #    #______"
echo "# #    #______"
echo "########______"
echo "COMMENT FRAME 5 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "__#####______"
echo "_#   ##______"
echo "#######______"
echo "#   # #______"
echo "#   # #______"
echo "######_______"
echo "COMMENT FRAME 1 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_#   ##______"
echo "#######______"
echo "##   ##______"
echo "##   ##______"
echo "#######_______"
echo "COMMENT FRAME 2 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_##   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 3 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "######_______"
echo "###   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 4 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "#######______"
echo "# #    #______"
echo "########______"
echo "# #    #______"
echo "# #    #______"
echo "########______"
echo "COMMENT FRAME 5 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "__#####______"
echo "_#   ##______"
echo "#######______"
echo "#   # #______"
echo "#   # #______"
echo "######_______"
echo "COMMENT FRAME 1 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_#   ##______"
echo "#######______"
echo "##   ##______"
echo "##   ##______"
echo "#######_______"
echo "COMMENT FRAME 2 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_##   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 3 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "######_______"
echo "###   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 4 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "#######______"
echo "# #    #______"
echo "########______"
echo "# #    #______"
echo "# #    #______"
echo "########______"
echo "COMMENT FRAME 5 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "__#####______"
echo "_#   ##______"
echo "#######______"
echo "#   # #______"
echo "#   # #______"
echo "######_______"
echo "COMMENT FRAME 1 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_#   ##______"
echo "#######______"
echo "##   ##______"
echo "##   ##______"
echo "#######_______"
echo "COMMENT FRAME 2 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_##   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 3 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "######_______"
echo "###   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 4 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "#######______"
echo "# #    #______"
echo "########______"
echo "# #    #______"
echo "# #    #______"
echo "########______"
echo "COMMENT FRAME 5 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "__#####______"
echo "_#   ##______"
echo "#######______"
echo "#   # #______"
echo "#   # #______"
echo "######_______"
echo "COMMENT FRAME 1 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_#   ##______"
echo "#######______"
echo "##   ##______"
echo "##   ##______"
echo "#######_______"
echo "COMMENT FRAME 2 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_##   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 3 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "######_______"
echo "###   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 4 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "#######______"
echo "# #    #______"
echo "########______"
echo "# #    #______"
echo "# #    #______"
echo "########______"
echo "COMMENT FRAME 5 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "__#####______"
echo "_#   ##______"
echo "#######______"
echo "#   # #______"
echo "#   # #______"
echo "######_______"
echo "COMMENT FRAME 1 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_#   ##______"
echo "#######______"
echo "##   ##______"
echo "##   ##______"
echo "#######_______"
echo "COMMENT FRAME 2 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "_######______"
echo "_##   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 3 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "######_______"
echo "###   #______"
echo "#######______"
echo "###   #______"
echo "###   #______"
echo "#######______"
echo "COMMENT FRAME 4 DRAWN"
echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "____________"
echo "____________"
echo "#######______"
echo "# #    #______"
echo "########______"
echo "# #    #______"
echo "# #    #______"
echo "########______"
echo "COMMENT FRAME 5 DRAWN"