echo "__________"
echo "Books Programs Words 3"
echo "___________"
echo "Console Window"
echo "cmd string"
echo "cmd string"
echo "cmd string"
echo "__________"
echo "file browser"
echo "__________"
echo "_[__]_[__]_"
echo "_[__]_[__]_"
echo "__________"
echo "_/--\_/--\_"
echo "____________"
echo "#####_______"
echo "#####_______"
echo "#####_______"
echo "#####_______"
